name: env_cooking
channels:
  - conda-forge
dependencies:
  - python=3.10
  - transformers=4.30.2
  - diffusers=0.16.1
  - matplotlib
  - pandas
  - numpy  
  - pip
  # - jupyter
  # - ipykernel
  - openai=0.28  
  # - axios
  - pip:
    - langchain[all]
    - langchain-community
    - flask
    - pydantic 